### PR TITLE
Updated/cleaned up according to current catkin and travis style guides

### PR DESCRIPTION
**Pull request by ipa-rmb**
- should build with travis now
- sorry for the big number of files, this comes from cob_3d_mapping_geometry_map_v2 and is the copy of all headers of the boost library ver 1.59 (necessary for that project) - I could not successfully take these out to a separate wrapper package, because then the system boost installation (headers+libs) would conflict with the headers-only in the install space
- we should open PR #37 again for getting the travis config up-to-date

### CODE REVIEW

**Comment by ipa-rmb** [comment]
Can someone with respective rights activate the travis service hook for this repository, please? So that the travis result is directly visible here. @ipa-fxm ?

**Comment by ipa-rmb** [comment]
Ok, now travis output is visible in this PR.

**Comment by fmessmer** [comment]
I guess without further stripping down the package, you won't be able to stay below 50 mins...some ideas:
 - do you install dependencies that you do not need/take long to download? tex-fonts?
 - maybe a different docker image could help? @ipa-mdl
 - could you profile a bit which package takes the longest when you run it locally on your pc?
 - can the boost stuff be resolved differently, i.e. rewrite code a bit rather than committing 2x10^6 lines of code?
 - are there any executables/libraries/tests that are kind of optional or no longer use? you could remove/comment them in the CMakeLists.txt

**Comment by mathias-luedtke** [comment]
Please don't add `brics_actuator`! Remove it and all depending packges/code.

> maybe a different docker image could help? @ipa-mdl

rosdep takes 9 minutes, this could be avoided by a custom image with all dependencies.

>  can the boost stuff be resolved differently, i.e. rewrite code a bit rather than committing 2x10^6 lines of code?

Don't check in the boost code!
If needed, it should get downladed at build time.

> are there any executables/libraries/tests that are kind of optional or no longer use?

Perhaps some packages can be moved into a new 
`cob_environment_perception_experimental` repository.

**Comment by mathias-luedtke** [comment]
Which node is publishing to the `command_pos` of the demonstrator?

**Comment by ipa-rmb** [comment]
test_clientPOS and test_client, I would say.

**Comment by mathias-luedtke** [comment]
> test_clientPOS and test_client, I would say.

These could be refactored to use the action interface, and perhaps they are not needed at all..

**Pull request merged**
